use super::types::{CisRule, RuleCategory, Severity};

pub fn get_all_rules() -> Vec<CisRule> {
    vec![
        // Section 2: Daemon Configuration (2 rules)
        CisRule {
            id: "2.10".to_string(),
            title: "Enable user namespace support".to_string(),
            category: RuleCategory::Namespace,
            severity: Severity::High,
            section: "Daemon".to_string(),
            description: "User namespaces restrict the privileges of a user within a container.".to_string(),
            remediation: "Ensure that 'userns-remap' is configured in /etc/docker/daemon.json.".to_string(),
        },
        CisRule {
            id: "2.11".to_string(),
            title: "Default cgroup usage confirmed".to_string(),
            category: RuleCategory::Cgroup,
            severity: Severity::Medium,
            section: "Daemon".to_string(),
            description: "It is a good practice to use the default cgroup-parent for containers, avoiding assigning them to custom, potentially conflicting cgroups.".to_string(),
            remediation: "Review /etc/docker/daemon.json and ensure 'cgroup-parent' is not improperly configured.".to_string(),
        },

        // Section 3: Docker Daemon Configuration Files (8 rules)
        CisRule {
            id: "3.1".to_string(),
            title: "Ensure that the docker.service file ownership is set to root:root".to_string(),
            category: RuleCategory::Files,
            severity: Severity::High,
            section: "Docker daemon configuration files".to_string(),
            description: "The docker.service file contains sensitive parameters that may alter the behavior of the Docker daemon. It should be owned by root:root.".to_string(),
            remediation: "chown root:root /usr/lib/systemd/system/docker.service".to_string(),
        },
        CisRule {
            id: "3.2".to_string(),
            title: "Ensure that docker.service file permissions are appropriately set".to_string(),
            category: RuleCategory::Files,
            severity: Severity::High,
            section: "Docker daemon configuration files".to_string(),
            description: "The docker.service file should have permissions of 644 or more restrictive to maintain the integrity of the file.".to_string(),
            remediation: "chmod 644 /usr/lib/systemd/system/docker.service".to_string(),
        },
        CisRule {
            id: "3.5".to_string(),
            title: "Ensure that the /etc/docker directory ownership is set to root:root".to_string(),
            category: RuleCategory::Files,
            severity: Severity::High,
            section: "Docker daemon configuration files".to_string(),
            description: "The /etc/docker directory contains certificates and keys in addition to various sensitive files. It should be owned by root:root.".to_string(),
            remediation: "chown root:root /etc/docker".to_string(),
        },
        CisRule {
            id: "3.6".to_string(),
            title: "Ensure that /etc/docker directory permissions are set to 755 or more restrictively".to_string(),
            category: RuleCategory::Files,
            severity: Severity::High,
            section: "Docker daemon configuration files".to_string(),
            description: "The /etc/docker directory contains certificates and keys in addition to various sensitive files. It should have permissions of 755 or more restrictive.".to_string(),
            remediation: "chmod 755 /etc/docker".to_string(),
        },
        CisRule {
            id: "3.15".to_string(),
            title: "Ensure that the Docker socket file ownership is set to root:docker".to_string(),
            category: RuleCategory::Files,
            severity: Severity::High,
            section: "Docker daemon configuration files".to_string(),
            description: "The Docker socket file should be owned by root:docker to maintain the integrity of the socket file.".to_string(),
            remediation: "chown root:docker /var/run/docker.sock".to_string(),
        },
        CisRule {
            id: "3.16".to_string(),
            title: "Ensure that the Docker socket file permissions are set to 660 or more restrictively".to_string(),
            category: RuleCategory::Files,
            severity: Severity::High,
            section: "Docker daemon configuration files".to_string(),
            description: "Only root and members of the docker group should be able to read and write to the Docker socket file.".to_string(),
            remediation: "chmod 660 /var/run/docker.sock".to_string(),
        },
        CisRule {
            id: "3.17".to_string(),
            title: "Ensure that the daemon.json file ownership is set to root:root".to_string(),
            category: RuleCategory::Files,
            severity: Severity::High,
            section: "Docker daemon configuration files".to_string(),
            description: "The daemon.json file contains sensitive parameters that may alter the behavior of the Docker daemon. It should be owned by root:root.".to_string(),
            remediation: "chown root:root /etc/docker/daemon.json".to_string(),
        },
        CisRule {
            id: "3.18".to_string(),
            title: "Ensure that daemon.json file permissions are set to 644 or more restrictive".to_string(),
            category: RuleCategory::Files,
            severity: Severity::High,
            section: "Docker daemon configuration files".to_string(),
            description: "The daemon.json file should have permissions of 644 or more restrictive to maintain the integrity of the file.".to_string(),
            remediation: "chmod 644 /etc/docker/daemon.json".to_string(),
        },

        // Section 5: Container Runtime (20 rules)
        CisRule {
            id: "5.2".to_string(),
            title: "Ensure that, if applicable, an AppArmor Profile is enabled".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::Medium,
            section: "Container Runtime".to_string(),
            description: "AppArmor is an effective and easy-to-use Linux application security system. It is available on some Linux distributions by default.".to_string(),
            remediation: "Start containers with '--security-opt apparmor=<profile>' or use a default profile.".to_string(),
        },
        CisRule {
            id: "5.3".to_string(),
            title: "Ensure that, if applicable, SELinux security options are set".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::Medium,
            section: "Container Runtime".to_string(),
            description: "SELinux provides a Mandatory Access Control (MAC) system that greatly augments the default Discretionary Access Control (DAC) model.".to_string(),
            remediation: "Start containers with '--security-opt label=<level>' to set SELinux labels.".to_string(),
        },
        CisRule {
            id: "5.4".to_string(),
            title: "Ensure that Linux kernel capabilities are restricted within containers".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "By default, Docker starts containers with a restricted set of Linux kernel capabilities. You should not add capabilities beyond the default set.".to_string(),
            remediation: "Use '--cap-drop=ALL' and only add required capabilities with '--cap-add'.".to_string(),
        },
        CisRule {
            id: "5.5".to_string(),
            title: "Ensure that privileged containers are not used".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "Using the --privileged flag gives all Linux kernel capabilities to the container and also lifts all the limitations enforced by the device cgroup controller.".to_string(),
            remediation: "Do not run containers with the '--privileged' flag.".to_string(),
        },
        CisRule {
            id: "5.6".to_string(),
            title: "Ensure sensitive host system directories are not mounted on containers".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "Sensitive host system directories such as '/', '/boot', '/dev', '/etc', '/lib', '/proc', '/sys', '/usr' should not be mounted on containers.".to_string(),
            remediation: "Do not mount host sensitive directories on containers especially in read-write mode.".to_string(),
        },
        CisRule {
            id: "5.8".to_string(),
            title: "Ensure privileged ports are not mapped within containers".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::Medium,
            section: "Container Runtime".to_string(),
            description: "The TCP/IP port numbers below 1024 are considered privileged ports. Normal users and processes are not allowed to use them.".to_string(),
            remediation: "Do not map container ports to privileged host ports (below 1024).".to_string(),
        },
        CisRule {
            id: "5.10".to_string(),
            title: "Host's network namespace not shared".to_string(),
            category: RuleCategory::Namespace,
            severity: Severity::Medium,
            section: "Container Runtime".to_string(),
            description: "Do not use '--net=host' when starting a container so it does not share the host's network namespace.".to_string(),
            remediation: "Run the container without '--net=host'.".to_string(),
        },
        CisRule {
            id: "5.11".to_string(),
            title: "Memory usage limited".to_string(),
            category: RuleCategory::Cgroup,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "By default, all containers can use as much memory as they need. This could lead to a Denial of Service.".to_string(),
            remediation: "Start a container with '--memory' parameter.".to_string(),
        },
        CisRule {
            id: "5.12".to_string(),
            title: "CPU priority set appropriately".to_string(),
            category: RuleCategory::Cgroup,
            severity: Severity::Medium,
            section: "Container Runtime".to_string(),
            description: "By default, all containers get the same proportion of CPU cycles. This rule checks if CPU shares are explicitly configured.".to_string(),
            remediation: "Start a container with '--cpu-shares' parameter.".to_string(),
        },
        CisRule {
            id: "5.13".to_string(),
            title: "Ensure that the container's root filesystem is mounted as read only".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "The container's root filesystem should be treated as a 'golden image' and any writes should be made to a temporary filesystem.".to_string(),
            remediation: "Start containers with '--read-only' flag and use volumes for writable data.".to_string(),
        },
        CisRule {
            id: "5.16".to_string(),
            title: "Host's process namespace not shared".to_string(),
            category: RuleCategory::Namespace,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "A container should not share the host's process namespace, preventing it from seeing or interacting with host processes.".to_string(),
            remediation: "Do not start a container with '--pid=host'.".to_string(),
        },
        CisRule {
            id: "5.17".to_string(),
            title: "Host's IPC namespace not shared".to_string(),
            category: RuleCategory::Namespace,
            severity: Severity::Medium,
            section: "Container Runtime".to_string(),
            description: "A container should not share the host's IPC namespace, preventing IPC communication with the host.".to_string(),
            remediation: "Do not start a container with '--ipc=host'.".to_string(),
        },
        CisRule {
            id: "5.21".to_string(),
            title: "Host's UTS namespace not shared".to_string(),
            category: RuleCategory::Namespace,
            severity: Severity::Medium,
            section: "Container Runtime".to_string(),
            description: "A container should not share the host's UTS namespace, allowing the container to have its own hostname.".to_string(),
            remediation: "Do not start a container with '--uts=host'.".to_string(),
        },
        CisRule {
            id: "5.22".to_string(),
            title: "Ensure the default seccomp profile is not Disabled".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "Seccomp filtering provides a means for a process to specify a filter for incoming system calls. The default Docker seccomp profile works on whitelist basis.".to_string(),
            remediation: "Do not disable the default seccomp profile with '--security-opt seccomp=unconfined'.".to_string(),
        },
        CisRule {
            id: "5.25".to_string(),
            title: "Cgroup usage confirmed (no privileged)".to_string(),
            category: RuleCategory::Cgroup,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "Privileged containers can break cgroup isolations trivially.".to_string(),
            remediation: "Avoid using '--privileged' when starting a container.".to_string(),
        },
        CisRule {
            id: "5.26".to_string(),
            title: "Restricted from additional privileges".to_string(),
            category: RuleCategory::Cgroup,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "A process can acquire more privileges than from its parent, preventing this limits attack surface.".to_string(),
            remediation: "Start a container with '--security-opt=no-new-privileges'.".to_string(),
        },
        CisRule {
            id: "5.27".to_string(),
            title: "Ensure that container health is checked at runtime".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::Medium,
            section: "Container Runtime".to_string(),
            description: "If the container image does not have an HEALTHCHECK instruction defined, use --health-cmd parameter at container runtime.".to_string(),
            remediation: "Add HEALTHCHECK to Dockerfile or use '--health-cmd' at runtime.".to_string(),
        },
        CisRule {
            id: "5.29".to_string(),
            title: "PIDs cgroup limit used".to_string(),
            category: RuleCategory::Cgroup,
            severity: Severity::Medium,
            section: "Container Runtime".to_string(),
            description: "Use --pids-limit to prevent fork bombs and limit the number of processes in a container.".to_string(),
            remediation: "Start a container with '--pids-limit' parameter.".to_string(),
        },
        CisRule {
            id: "5.31".to_string(),
            title: "Host's user namespaces not shared".to_string(),
            category: RuleCategory::Namespace,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "A container should not share the host's user namespaces.".to_string(),
            remediation: "Do not start a container with '--userns=host'.".to_string(),
        },
        CisRule {
            id: "5.32".to_string(),
            title: "Ensure that the Docker socket is not mounted inside any containers".to_string(),
            category: RuleCategory::Runtime,
            severity: Severity::High,
            section: "Container Runtime".to_string(),
            description: "Mounting the Docker socket inside a container allows the container to control the Docker daemon on the host.".to_string(),
            remediation: "Do not mount '/var/run/docker.sock' inside containers.".to_string(),
        },
    ]
}

pub fn get_rule_by_id(id: &str) -> Option<CisRule> {
    get_all_rules().into_iter().find(|r| r.id == id)
}
