FROM rust:1.88-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

# Install sqlx-cli
RUN cargo install sqlx-cli --no-default-features --features postgres

# Copy migrations
COPY migrations ./migrations

# Run migrations
CMD ["sqlx", "migrate", "run"]
