/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SettingsSessionsRouteImport } from './routes/settings/sessions'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedAgentsIdIndexRouteImport } from './routes/_authenticated/agents.$id.index'
import { Route as AuthenticatedAgentsIdVolumesRouteImport } from './routes/_authenticated/agents.$id.volumes'
import { Route as AuthenticatedAgentsIdNetworksRouteImport } from './routes/_authenticated/agents.$id.networks'
import { Route as AuthenticatedAgentsIdImagesRouteImport } from './routes/_authenticated/agents.$id.images'
import { Route as AuthenticatedAgentsIdEventsRouteImport } from './routes/_authenticated/agents.$id.events'
import { Route as AuthenticatedAgentsIdContainersRouteImport } from './routes/_authenticated/agents.$id.containers'
import { Route as AuthenticatedAgentsIdAuditsRouteImport } from './routes/_authenticated/agents.$id.audits'
import { Route as AuthenticatedAgentsIdAuditRouteImport } from './routes/_authenticated/agents.$id.audit'
import { Route as AuthenticatedAgentsIdAuditsIndexRouteImport } from './routes/_authenticated/agents.$id.audits.index'
import { Route as AuthenticatedAgentsIdAuditIndexRouteImport } from './routes/_authenticated/agents.$id.audit.index'
import { Route as AuthenticatedAgentsIdVolumesVolumeNameRouteImport } from './routes/_authenticated/agents.$id.volumes.$volumeName'
import { Route as AuthenticatedAgentsIdNetworksNetworkIdRouteImport } from './routes/_authenticated/agents.$id.networks.$networkId'
import { Route as AuthenticatedAgentsIdImagesImageIdRouteImport } from './routes/_authenticated/agents.$id.images.$imageId'
import { Route as AuthenticatedAgentsIdAuditsAuditIdRouteImport } from './routes/_authenticated/agents.$id.audits.$auditId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SettingsSessionsRoute = SettingsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAgentsIdIndexRoute =
  AuthenticatedAgentsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdVolumesRoute =
  AuthenticatedAgentsIdVolumesRouteImport.update({
    id: '/volumes',
    path: '/volumes',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdNetworksRoute =
  AuthenticatedAgentsIdNetworksRouteImport.update({
    id: '/networks',
    path: '/networks',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdImagesRoute =
  AuthenticatedAgentsIdImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdEventsRoute =
  AuthenticatedAgentsIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdContainersRoute =
  AuthenticatedAgentsIdContainersRouteImport.update({
    id: '/containers',
    path: '/containers',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdAuditsRoute =
  AuthenticatedAgentsIdAuditsRouteImport.update({
    id: '/audits',
    path: '/audits',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdAuditRoute =
  AuthenticatedAgentsIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdAuditsIndexRoute =
  AuthenticatedAgentsIdAuditsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdAuditsRoute,
  } as any)
const AuthenticatedAgentsIdAuditIndexRoute =
  AuthenticatedAgentsIdAuditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdAuditRoute,
  } as any)
const AuthenticatedAgentsIdVolumesVolumeNameRoute =
  AuthenticatedAgentsIdVolumesVolumeNameRouteImport.update({
    id: '/$volumeName',
    path: '/$volumeName',
    getParentRoute: () => AuthenticatedAgentsIdVolumesRoute,
  } as any)
const AuthenticatedAgentsIdNetworksNetworkIdRoute =
  AuthenticatedAgentsIdNetworksNetworkIdRouteImport.update({
    id: '/$networkId',
    path: '/$networkId',
    getParentRoute: () => AuthenticatedAgentsIdNetworksRoute,
  } as any)
const AuthenticatedAgentsIdImagesImageIdRoute =
  AuthenticatedAgentsIdImagesImageIdRouteImport.update({
    id: '/$imageId',
    path: '/$imageId',
    getParentRoute: () => AuthenticatedAgentsIdImagesRoute,
  } as any)
const AuthenticatedAgentsIdAuditsAuditIdRoute =
  AuthenticatedAgentsIdAuditsAuditIdRouteImport.update({
    id: '/$auditId',
    path: '/$auditId',
    getParentRoute: () => AuthenticatedAgentsIdAuditsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/agents/$id/audit': typeof AuthenticatedAgentsIdAuditRouteWithChildren
  '/agents/$id/audits': typeof AuthenticatedAgentsIdAuditsRouteWithChildren
  '/agents/$id/containers': typeof AuthenticatedAgentsIdContainersRoute
  '/agents/$id/events': typeof AuthenticatedAgentsIdEventsRoute
  '/agents/$id/images': typeof AuthenticatedAgentsIdImagesRouteWithChildren
  '/agents/$id/networks': typeof AuthenticatedAgentsIdNetworksRouteWithChildren
  '/agents/$id/volumes': typeof AuthenticatedAgentsIdVolumesRouteWithChildren
  '/agents/$id/': typeof AuthenticatedAgentsIdIndexRoute
  '/agents/$id/audits/$auditId': typeof AuthenticatedAgentsIdAuditsAuditIdRoute
  '/agents/$id/images/$imageId': typeof AuthenticatedAgentsIdImagesImageIdRoute
  '/agents/$id/networks/$networkId': typeof AuthenticatedAgentsIdNetworksNetworkIdRoute
  '/agents/$id/volumes/$volumeName': typeof AuthenticatedAgentsIdVolumesVolumeNameRoute
  '/agents/$id/audit/': typeof AuthenticatedAgentsIdAuditIndexRoute
  '/agents/$id/audits/': typeof AuthenticatedAgentsIdAuditsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/agents/$id/containers': typeof AuthenticatedAgentsIdContainersRoute
  '/agents/$id/events': typeof AuthenticatedAgentsIdEventsRoute
  '/agents/$id/images': typeof AuthenticatedAgentsIdImagesRouteWithChildren
  '/agents/$id/networks': typeof AuthenticatedAgentsIdNetworksRouteWithChildren
  '/agents/$id/volumes': typeof AuthenticatedAgentsIdVolumesRouteWithChildren
  '/agents/$id': typeof AuthenticatedAgentsIdIndexRoute
  '/agents/$id/audits/$auditId': typeof AuthenticatedAgentsIdAuditsAuditIdRoute
  '/agents/$id/images/$imageId': typeof AuthenticatedAgentsIdImagesImageIdRoute
  '/agents/$id/networks/$networkId': typeof AuthenticatedAgentsIdNetworksNetworkIdRoute
  '/agents/$id/volumes/$volumeName': typeof AuthenticatedAgentsIdVolumesVolumeNameRoute
  '/agents/$id/audit': typeof AuthenticatedAgentsIdAuditIndexRoute
  '/agents/$id/audits': typeof AuthenticatedAgentsIdAuditsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/agents/$id/audit': typeof AuthenticatedAgentsIdAuditRouteWithChildren
  '/_authenticated/agents/$id/audits': typeof AuthenticatedAgentsIdAuditsRouteWithChildren
  '/_authenticated/agents/$id/containers': typeof AuthenticatedAgentsIdContainersRoute
  '/_authenticated/agents/$id/events': typeof AuthenticatedAgentsIdEventsRoute
  '/_authenticated/agents/$id/images': typeof AuthenticatedAgentsIdImagesRouteWithChildren
  '/_authenticated/agents/$id/networks': typeof AuthenticatedAgentsIdNetworksRouteWithChildren
  '/_authenticated/agents/$id/volumes': typeof AuthenticatedAgentsIdVolumesRouteWithChildren
  '/_authenticated/agents/$id/': typeof AuthenticatedAgentsIdIndexRoute
  '/_authenticated/agents/$id/audits/$auditId': typeof AuthenticatedAgentsIdAuditsAuditIdRoute
  '/_authenticated/agents/$id/images/$imageId': typeof AuthenticatedAgentsIdImagesImageIdRoute
  '/_authenticated/agents/$id/networks/$networkId': typeof AuthenticatedAgentsIdNetworksNetworkIdRoute
  '/_authenticated/agents/$id/volumes/$volumeName': typeof AuthenticatedAgentsIdVolumesVolumeNameRoute
  '/_authenticated/agents/$id/audit/': typeof AuthenticatedAgentsIdAuditIndexRoute
  '/_authenticated/agents/$id/audits/': typeof AuthenticatedAgentsIdAuditsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/admin'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/settings/'
    | '/admin/api-keys'
    | '/admin/users'
    | '/agents/$id'
    | '/admin/'
    | '/agents/'
    | '/agents/$id/audit'
    | '/agents/$id/audits'
    | '/agents/$id/containers'
    | '/agents/$id/events'
    | '/agents/$id/images'
    | '/agents/$id/networks'
    | '/agents/$id/volumes'
    | '/agents/$id/'
    | '/agents/$id/audits/$auditId'
    | '/agents/$id/images/$imageId'
    | '/agents/$id/networks/$networkId'
    | '/agents/$id/volumes/$volumeName'
    | '/agents/$id/audit/'
    | '/agents/$id/audits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/'
    | '/settings'
    | '/admin/api-keys'
    | '/admin/users'
    | '/admin'
    | '/agents'
    | '/agents/$id/containers'
    | '/agents/$id/events'
    | '/agents/$id/images'
    | '/agents/$id/networks'
    | '/agents/$id/volumes'
    | '/agents/$id'
    | '/agents/$id/audits/$auditId'
    | '/agents/$id/images/$imageId'
    | '/agents/$id/networks/$networkId'
    | '/agents/$id/volumes/$volumeName'
    | '/agents/$id/audit'
    | '/agents/$id/audits'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/settings'
    | '/_authenticated/admin'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/_authenticated/'
    | '/settings/'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/users'
    | '/_authenticated/agents/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/agents/'
    | '/_authenticated/agents/$id/audit'
    | '/_authenticated/agents/$id/audits'
    | '/_authenticated/agents/$id/containers'
    | '/_authenticated/agents/$id/events'
    | '/_authenticated/agents/$id/images'
    | '/_authenticated/agents/$id/networks'
    | '/_authenticated/agents/$id/volumes'
    | '/_authenticated/agents/$id/'
    | '/_authenticated/agents/$id/audits/$auditId'
    | '/_authenticated/agents/$id/images/$imageId'
    | '/_authenticated/agents/$id/networks/$networkId'
    | '/_authenticated/agents/$id/volumes/$volumeName'
    | '/_authenticated/agents/$id/audit/'
    | '/_authenticated/agents/$id/audits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/settings/sessions': {
      id: '/settings/sessions'
      path: '/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingsSessionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/agents/$id/': {
      id: '/_authenticated/agents/$id/'
      path: '/'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AuthenticatedAgentsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/volumes': {
      id: '/_authenticated/agents/$id/volumes'
      path: '/volumes'
      fullPath: '/agents/$id/volumes'
      preLoaderRoute: typeof AuthenticatedAgentsIdVolumesRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/networks': {
      id: '/_authenticated/agents/$id/networks'
      path: '/networks'
      fullPath: '/agents/$id/networks'
      preLoaderRoute: typeof AuthenticatedAgentsIdNetworksRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/images': {
      id: '/_authenticated/agents/$id/images'
      path: '/images'
      fullPath: '/agents/$id/images'
      preLoaderRoute: typeof AuthenticatedAgentsIdImagesRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/events': {
      id: '/_authenticated/agents/$id/events'
      path: '/events'
      fullPath: '/agents/$id/events'
      preLoaderRoute: typeof AuthenticatedAgentsIdEventsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/containers': {
      id: '/_authenticated/agents/$id/containers'
      path: '/containers'
      fullPath: '/agents/$id/containers'
      preLoaderRoute: typeof AuthenticatedAgentsIdContainersRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/audits': {
      id: '/_authenticated/agents/$id/audits'
      path: '/audits'
      fullPath: '/agents/$id/audits'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/audit': {
      id: '/_authenticated/agents/$id/audit'
      path: '/audit'
      fullPath: '/agents/$id/audit'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/audits/': {
      id: '/_authenticated/agents/$id/audits/'
      path: '/'
      fullPath: '/agents/$id/audits/'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditsIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdAuditsRoute
    }
    '/_authenticated/agents/$id/audit/': {
      id: '/_authenticated/agents/$id/audit/'
      path: '/'
      fullPath: '/agents/$id/audit/'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdAuditRoute
    }
    '/_authenticated/agents/$id/volumes/$volumeName': {
      id: '/_authenticated/agents/$id/volumes/$volumeName'
      path: '/$volumeName'
      fullPath: '/agents/$id/volumes/$volumeName'
      preLoaderRoute: typeof AuthenticatedAgentsIdVolumesVolumeNameRouteImport
      parentRoute: typeof AuthenticatedAgentsIdVolumesRoute
    }
    '/_authenticated/agents/$id/networks/$networkId': {
      id: '/_authenticated/agents/$id/networks/$networkId'
      path: '/$networkId'
      fullPath: '/agents/$id/networks/$networkId'
      preLoaderRoute: typeof AuthenticatedAgentsIdNetworksNetworkIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdNetworksRoute
    }
    '/_authenticated/agents/$id/images/$imageId': {
      id: '/_authenticated/agents/$id/images/$imageId'
      path: '/$imageId'
      fullPath: '/agents/$id/images/$imageId'
      preLoaderRoute: typeof AuthenticatedAgentsIdImagesImageIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdImagesRoute
    }
    '/_authenticated/agents/$id/audits/$auditId': {
      id: '/_authenticated/agents/$id/audits/$auditId'
      path: '/$auditId'
      fullPath: '/agents/$id/audits/$auditId'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditsAuditIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdAuditsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAgentsIdAuditRouteChildren {
  AuthenticatedAgentsIdAuditIndexRoute: typeof AuthenticatedAgentsIdAuditIndexRoute
}

const AuthenticatedAgentsIdAuditRouteChildren: AuthenticatedAgentsIdAuditRouteChildren =
  {
    AuthenticatedAgentsIdAuditIndexRoute: AuthenticatedAgentsIdAuditIndexRoute,
  }

const AuthenticatedAgentsIdAuditRouteWithChildren =
  AuthenticatedAgentsIdAuditRoute._addFileChildren(
    AuthenticatedAgentsIdAuditRouteChildren,
  )

interface AuthenticatedAgentsIdAuditsRouteChildren {
  AuthenticatedAgentsIdAuditsAuditIdRoute: typeof AuthenticatedAgentsIdAuditsAuditIdRoute
  AuthenticatedAgentsIdAuditsIndexRoute: typeof AuthenticatedAgentsIdAuditsIndexRoute
}

const AuthenticatedAgentsIdAuditsRouteChildren: AuthenticatedAgentsIdAuditsRouteChildren =
  {
    AuthenticatedAgentsIdAuditsAuditIdRoute:
      AuthenticatedAgentsIdAuditsAuditIdRoute,
    AuthenticatedAgentsIdAuditsIndexRoute:
      AuthenticatedAgentsIdAuditsIndexRoute,
  }

const AuthenticatedAgentsIdAuditsRouteWithChildren =
  AuthenticatedAgentsIdAuditsRoute._addFileChildren(
    AuthenticatedAgentsIdAuditsRouteChildren,
  )

interface AuthenticatedAgentsIdImagesRouteChildren {
  AuthenticatedAgentsIdImagesImageIdRoute: typeof AuthenticatedAgentsIdImagesImageIdRoute
}

const AuthenticatedAgentsIdImagesRouteChildren: AuthenticatedAgentsIdImagesRouteChildren =
  {
    AuthenticatedAgentsIdImagesImageIdRoute:
      AuthenticatedAgentsIdImagesImageIdRoute,
  }

const AuthenticatedAgentsIdImagesRouteWithChildren =
  AuthenticatedAgentsIdImagesRoute._addFileChildren(
    AuthenticatedAgentsIdImagesRouteChildren,
  )

interface AuthenticatedAgentsIdNetworksRouteChildren {
  AuthenticatedAgentsIdNetworksNetworkIdRoute: typeof AuthenticatedAgentsIdNetworksNetworkIdRoute
}

const AuthenticatedAgentsIdNetworksRouteChildren: AuthenticatedAgentsIdNetworksRouteChildren =
  {
    AuthenticatedAgentsIdNetworksNetworkIdRoute:
      AuthenticatedAgentsIdNetworksNetworkIdRoute,
  }

const AuthenticatedAgentsIdNetworksRouteWithChildren =
  AuthenticatedAgentsIdNetworksRoute._addFileChildren(
    AuthenticatedAgentsIdNetworksRouteChildren,
  )

interface AuthenticatedAgentsIdVolumesRouteChildren {
  AuthenticatedAgentsIdVolumesVolumeNameRoute: typeof AuthenticatedAgentsIdVolumesVolumeNameRoute
}

const AuthenticatedAgentsIdVolumesRouteChildren: AuthenticatedAgentsIdVolumesRouteChildren =
  {
    AuthenticatedAgentsIdVolumesVolumeNameRoute:
      AuthenticatedAgentsIdVolumesVolumeNameRoute,
  }

const AuthenticatedAgentsIdVolumesRouteWithChildren =
  AuthenticatedAgentsIdVolumesRoute._addFileChildren(
    AuthenticatedAgentsIdVolumesRouteChildren,
  )

interface AuthenticatedAgentsIdRouteChildren {
  AuthenticatedAgentsIdAuditRoute: typeof AuthenticatedAgentsIdAuditRouteWithChildren
  AuthenticatedAgentsIdAuditsRoute: typeof AuthenticatedAgentsIdAuditsRouteWithChildren
  AuthenticatedAgentsIdContainersRoute: typeof AuthenticatedAgentsIdContainersRoute
  AuthenticatedAgentsIdEventsRoute: typeof AuthenticatedAgentsIdEventsRoute
  AuthenticatedAgentsIdImagesRoute: typeof AuthenticatedAgentsIdImagesRouteWithChildren
  AuthenticatedAgentsIdNetworksRoute: typeof AuthenticatedAgentsIdNetworksRouteWithChildren
  AuthenticatedAgentsIdVolumesRoute: typeof AuthenticatedAgentsIdVolumesRouteWithChildren
  AuthenticatedAgentsIdIndexRoute: typeof AuthenticatedAgentsIdIndexRoute
}

const AuthenticatedAgentsIdRouteChildren: AuthenticatedAgentsIdRouteChildren = {
  AuthenticatedAgentsIdAuditRoute: AuthenticatedAgentsIdAuditRouteWithChildren,
  AuthenticatedAgentsIdAuditsRoute:
    AuthenticatedAgentsIdAuditsRouteWithChildren,
  AuthenticatedAgentsIdContainersRoute: AuthenticatedAgentsIdContainersRoute,
  AuthenticatedAgentsIdEventsRoute: AuthenticatedAgentsIdEventsRoute,
  AuthenticatedAgentsIdImagesRoute:
    AuthenticatedAgentsIdImagesRouteWithChildren,
  AuthenticatedAgentsIdNetworksRoute:
    AuthenticatedAgentsIdNetworksRouteWithChildren,
  AuthenticatedAgentsIdVolumesRoute:
    AuthenticatedAgentsIdVolumesRouteWithChildren,
  AuthenticatedAgentsIdIndexRoute: AuthenticatedAgentsIdIndexRoute,
}

const AuthenticatedAgentsIdRouteWithChildren =
  AuthenticatedAgentsIdRoute._addFileChildren(
    AuthenticatedAgentsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRouteWithChildren
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRouteWithChildren,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SettingsRouteChildren {
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSessionsRoute: typeof SettingsSessionsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSessionsRoute: SettingsSessionsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
