/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailChangeRouteImport } from './routes/verify-email-change'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSettingsSessionsRouteImport } from './routes/_authenticated/settings/sessions'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminAuditsRouteImport } from './routes/_authenticated/admin/audits'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedAgentsIdIndexRouteImport } from './routes/_authenticated/agents.$id.index'
import { Route as AuthenticatedAgentsIdVolumesRouteImport } from './routes/_authenticated/agents.$id.volumes'
import { Route as AuthenticatedAgentsIdStacksRouteImport } from './routes/_authenticated/agents.$id.stacks'
import { Route as AuthenticatedAgentsIdNetworksRouteImport } from './routes/_authenticated/agents.$id.networks'
import { Route as AuthenticatedAgentsIdImagesRouteImport } from './routes/_authenticated/agents.$id.images'
import { Route as AuthenticatedAgentsIdEventsRouteImport } from './routes/_authenticated/agents.$id.events'
import { Route as AuthenticatedAgentsIdContainersRouteImport } from './routes/_authenticated/agents.$id.containers'
import { Route as AuthenticatedAgentsIdAuditsRouteImport } from './routes/_authenticated/agents.$id.audits'
import { Route as AuthenticatedAgentsIdAuditRouteImport } from './routes/_authenticated/agents.$id.audit'
import { Route as AuthenticatedAgentsIdVolumesIndexRouteImport } from './routes/_authenticated/agents.$id.volumes.index'
import { Route as AuthenticatedAgentsIdStacksIndexRouteImport } from './routes/_authenticated/agents.$id.stacks.index'
import { Route as AuthenticatedAgentsIdNetworksIndexRouteImport } from './routes/_authenticated/agents.$id.networks.index'
import { Route as AuthenticatedAgentsIdImagesIndexRouteImport } from './routes/_authenticated/agents.$id.images.index'
import { Route as AuthenticatedAgentsIdContainersIndexRouteImport } from './routes/_authenticated/agents.$id.containers.index'
import { Route as AuthenticatedAgentsIdAuditsIndexRouteImport } from './routes/_authenticated/agents.$id.audits.index'
import { Route as AuthenticatedAgentsIdAuditIndexRouteImport } from './routes/_authenticated/agents.$id.audit.index'
import { Route as AuthenticatedAgentsIdVolumesVolumeNameRouteImport } from './routes/_authenticated/agents.$id.volumes.$volumeName'
import { Route as AuthenticatedAgentsIdNetworksNetworkIdRouteImport } from './routes/_authenticated/agents.$id.networks.$networkId'
import { Route as AuthenticatedAgentsIdImagesImageIdRouteImport } from './routes/_authenticated/agents.$id.images.$imageId'
import { Route as AuthenticatedAgentsIdContainersContainerIdRouteImport } from './routes/_authenticated/agents.$id.containers.$containerId'
import { Route as AuthenticatedAgentsIdAuditsAuditIdRouteImport } from './routes/_authenticated/agents.$id.audits.$auditId'

const VerifyEmailChangeRoute = VerifyEmailChangeRouteImport.update({
  id: '/verify-email-change',
  path: '/verify-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSettingsSessionsRoute =
  AuthenticatedSettingsSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditsRoute =
  AuthenticatedAdminAuditsRouteImport.update({
    id: '/audits',
    path: '/audits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAgentsIdIndexRoute =
  AuthenticatedAgentsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdVolumesRoute =
  AuthenticatedAgentsIdVolumesRouteImport.update({
    id: '/volumes',
    path: '/volumes',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdStacksRoute =
  AuthenticatedAgentsIdStacksRouteImport.update({
    id: '/stacks',
    path: '/stacks',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdNetworksRoute =
  AuthenticatedAgentsIdNetworksRouteImport.update({
    id: '/networks',
    path: '/networks',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdImagesRoute =
  AuthenticatedAgentsIdImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdEventsRoute =
  AuthenticatedAgentsIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdContainersRoute =
  AuthenticatedAgentsIdContainersRouteImport.update({
    id: '/containers',
    path: '/containers',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdAuditsRoute =
  AuthenticatedAgentsIdAuditsRouteImport.update({
    id: '/audits',
    path: '/audits',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdAuditRoute =
  AuthenticatedAgentsIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdVolumesIndexRoute =
  AuthenticatedAgentsIdVolumesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdVolumesRoute,
  } as any)
const AuthenticatedAgentsIdStacksIndexRoute =
  AuthenticatedAgentsIdStacksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdStacksRoute,
  } as any)
const AuthenticatedAgentsIdNetworksIndexRoute =
  AuthenticatedAgentsIdNetworksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdNetworksRoute,
  } as any)
const AuthenticatedAgentsIdImagesIndexRoute =
  AuthenticatedAgentsIdImagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdImagesRoute,
  } as any)
const AuthenticatedAgentsIdContainersIndexRoute =
  AuthenticatedAgentsIdContainersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdContainersRoute,
  } as any)
const AuthenticatedAgentsIdAuditsIndexRoute =
  AuthenticatedAgentsIdAuditsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdAuditsRoute,
  } as any)
const AuthenticatedAgentsIdAuditIndexRoute =
  AuthenticatedAgentsIdAuditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdAuditRoute,
  } as any)
const AuthenticatedAgentsIdVolumesVolumeNameRoute =
  AuthenticatedAgentsIdVolumesVolumeNameRouteImport.update({
    id: '/$volumeName',
    path: '/$volumeName',
    getParentRoute: () => AuthenticatedAgentsIdVolumesRoute,
  } as any)
const AuthenticatedAgentsIdNetworksNetworkIdRoute =
  AuthenticatedAgentsIdNetworksNetworkIdRouteImport.update({
    id: '/$networkId',
    path: '/$networkId',
    getParentRoute: () => AuthenticatedAgentsIdNetworksRoute,
  } as any)
const AuthenticatedAgentsIdImagesImageIdRoute =
  AuthenticatedAgentsIdImagesImageIdRouteImport.update({
    id: '/$imageId',
    path: '/$imageId',
    getParentRoute: () => AuthenticatedAgentsIdImagesRoute,
  } as any)
const AuthenticatedAgentsIdContainersContainerIdRoute =
  AuthenticatedAgentsIdContainersContainerIdRouteImport.update({
    id: '/$containerId',
    path: '/$containerId',
    getParentRoute: () => AuthenticatedAgentsIdContainersRoute,
  } as any)
const AuthenticatedAgentsIdAuditsAuditIdRoute =
  AuthenticatedAgentsIdAuditsAuditIdRouteImport.update({
    id: '/$auditId',
    path: '/$auditId',
    getParentRoute: () => AuthenticatedAgentsIdAuditsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-change': typeof VerifyEmailChangeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/audits': typeof AuthenticatedAdminAuditsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/sessions': typeof AuthenticatedSettingsSessionsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/agents/$id/audit': typeof AuthenticatedAgentsIdAuditRouteWithChildren
  '/agents/$id/audits': typeof AuthenticatedAgentsIdAuditsRouteWithChildren
  '/agents/$id/containers': typeof AuthenticatedAgentsIdContainersRouteWithChildren
  '/agents/$id/events': typeof AuthenticatedAgentsIdEventsRoute
  '/agents/$id/images': typeof AuthenticatedAgentsIdImagesRouteWithChildren
  '/agents/$id/networks': typeof AuthenticatedAgentsIdNetworksRouteWithChildren
  '/agents/$id/stacks': typeof AuthenticatedAgentsIdStacksRouteWithChildren
  '/agents/$id/volumes': typeof AuthenticatedAgentsIdVolumesRouteWithChildren
  '/agents/$id/': typeof AuthenticatedAgentsIdIndexRoute
  '/agents/$id/audits/$auditId': typeof AuthenticatedAgentsIdAuditsAuditIdRoute
  '/agents/$id/containers/$containerId': typeof AuthenticatedAgentsIdContainersContainerIdRoute
  '/agents/$id/images/$imageId': typeof AuthenticatedAgentsIdImagesImageIdRoute
  '/agents/$id/networks/$networkId': typeof AuthenticatedAgentsIdNetworksNetworkIdRoute
  '/agents/$id/volumes/$volumeName': typeof AuthenticatedAgentsIdVolumesVolumeNameRoute
  '/agents/$id/audit/': typeof AuthenticatedAgentsIdAuditIndexRoute
  '/agents/$id/audits/': typeof AuthenticatedAgentsIdAuditsIndexRoute
  '/agents/$id/containers/': typeof AuthenticatedAgentsIdContainersIndexRoute
  '/agents/$id/images/': typeof AuthenticatedAgentsIdImagesIndexRoute
  '/agents/$id/networks/': typeof AuthenticatedAgentsIdNetworksIndexRoute
  '/agents/$id/stacks/': typeof AuthenticatedAgentsIdStacksIndexRoute
  '/agents/$id/volumes/': typeof AuthenticatedAgentsIdVolumesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-change': typeof VerifyEmailChangeRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/audits': typeof AuthenticatedAdminAuditsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/sessions': typeof AuthenticatedSettingsSessionsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/agents/$id/events': typeof AuthenticatedAgentsIdEventsRoute
  '/agents/$id': typeof AuthenticatedAgentsIdIndexRoute
  '/agents/$id/audits/$auditId': typeof AuthenticatedAgentsIdAuditsAuditIdRoute
  '/agents/$id/containers/$containerId': typeof AuthenticatedAgentsIdContainersContainerIdRoute
  '/agents/$id/images/$imageId': typeof AuthenticatedAgentsIdImagesImageIdRoute
  '/agents/$id/networks/$networkId': typeof AuthenticatedAgentsIdNetworksNetworkIdRoute
  '/agents/$id/volumes/$volumeName': typeof AuthenticatedAgentsIdVolumesVolumeNameRoute
  '/agents/$id/audit': typeof AuthenticatedAgentsIdAuditIndexRoute
  '/agents/$id/audits': typeof AuthenticatedAgentsIdAuditsIndexRoute
  '/agents/$id/containers': typeof AuthenticatedAgentsIdContainersIndexRoute
  '/agents/$id/images': typeof AuthenticatedAgentsIdImagesIndexRoute
  '/agents/$id/networks': typeof AuthenticatedAgentsIdNetworksIndexRoute
  '/agents/$id/stacks': typeof AuthenticatedAgentsIdStacksIndexRoute
  '/agents/$id/volumes': typeof AuthenticatedAgentsIdVolumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-change': typeof VerifyEmailChangeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/audits': typeof AuthenticatedAdminAuditsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/sessions': typeof AuthenticatedSettingsSessionsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/agents/$id/audit': typeof AuthenticatedAgentsIdAuditRouteWithChildren
  '/_authenticated/agents/$id/audits': typeof AuthenticatedAgentsIdAuditsRouteWithChildren
  '/_authenticated/agents/$id/containers': typeof AuthenticatedAgentsIdContainersRouteWithChildren
  '/_authenticated/agents/$id/events': typeof AuthenticatedAgentsIdEventsRoute
  '/_authenticated/agents/$id/images': typeof AuthenticatedAgentsIdImagesRouteWithChildren
  '/_authenticated/agents/$id/networks': typeof AuthenticatedAgentsIdNetworksRouteWithChildren
  '/_authenticated/agents/$id/stacks': typeof AuthenticatedAgentsIdStacksRouteWithChildren
  '/_authenticated/agents/$id/volumes': typeof AuthenticatedAgentsIdVolumesRouteWithChildren
  '/_authenticated/agents/$id/': typeof AuthenticatedAgentsIdIndexRoute
  '/_authenticated/agents/$id/audits/$auditId': typeof AuthenticatedAgentsIdAuditsAuditIdRoute
  '/_authenticated/agents/$id/containers/$containerId': typeof AuthenticatedAgentsIdContainersContainerIdRoute
  '/_authenticated/agents/$id/images/$imageId': typeof AuthenticatedAgentsIdImagesImageIdRoute
  '/_authenticated/agents/$id/networks/$networkId': typeof AuthenticatedAgentsIdNetworksNetworkIdRoute
  '/_authenticated/agents/$id/volumes/$volumeName': typeof AuthenticatedAgentsIdVolumesVolumeNameRoute
  '/_authenticated/agents/$id/audit/': typeof AuthenticatedAgentsIdAuditIndexRoute
  '/_authenticated/agents/$id/audits/': typeof AuthenticatedAgentsIdAuditsIndexRoute
  '/_authenticated/agents/$id/containers/': typeof AuthenticatedAgentsIdContainersIndexRoute
  '/_authenticated/agents/$id/images/': typeof AuthenticatedAgentsIdImagesIndexRoute
  '/_authenticated/agents/$id/networks/': typeof AuthenticatedAgentsIdNetworksIndexRoute
  '/_authenticated/agents/$id/stacks/': typeof AuthenticatedAgentsIdStacksIndexRoute
  '/_authenticated/agents/$id/volumes/': typeof AuthenticatedAgentsIdVolumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-email-change'
    | '/admin'
    | '/settings'
    | '/admin/api-keys'
    | '/admin/audits'
    | '/admin/settings'
    | '/admin/users'
    | '/agents/$id'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/admin/'
    | '/agents/'
    | '/settings/'
    | '/agents/$id/audit'
    | '/agents/$id/audits'
    | '/agents/$id/containers'
    | '/agents/$id/events'
    | '/agents/$id/images'
    | '/agents/$id/networks'
    | '/agents/$id/stacks'
    | '/agents/$id/volumes'
    | '/agents/$id/'
    | '/agents/$id/audits/$auditId'
    | '/agents/$id/containers/$containerId'
    | '/agents/$id/images/$imageId'
    | '/agents/$id/networks/$networkId'
    | '/agents/$id/volumes/$volumeName'
    | '/agents/$id/audit/'
    | '/agents/$id/audits/'
    | '/agents/$id/containers/'
    | '/agents/$id/images/'
    | '/agents/$id/networks/'
    | '/agents/$id/stacks/'
    | '/agents/$id/volumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-email-change'
    | '/'
    | '/admin/api-keys'
    | '/admin/audits'
    | '/admin/settings'
    | '/admin/users'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/admin'
    | '/agents'
    | '/settings'
    | '/agents/$id/events'
    | '/agents/$id'
    | '/agents/$id/audits/$auditId'
    | '/agents/$id/containers/$containerId'
    | '/agents/$id/images/$imageId'
    | '/agents/$id/networks/$networkId'
    | '/agents/$id/volumes/$volumeName'
    | '/agents/$id/audit'
    | '/agents/$id/audits'
    | '/agents/$id/containers'
    | '/agents/$id/images'
    | '/agents/$id/networks'
    | '/agents/$id/stacks'
    | '/agents/$id/volumes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-email-change'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/audits'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/agents/$id'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/sessions'
    | '/_authenticated/admin/'
    | '/_authenticated/agents/'
    | '/_authenticated/settings/'
    | '/_authenticated/agents/$id/audit'
    | '/_authenticated/agents/$id/audits'
    | '/_authenticated/agents/$id/containers'
    | '/_authenticated/agents/$id/events'
    | '/_authenticated/agents/$id/images'
    | '/_authenticated/agents/$id/networks'
    | '/_authenticated/agents/$id/stacks'
    | '/_authenticated/agents/$id/volumes'
    | '/_authenticated/agents/$id/'
    | '/_authenticated/agents/$id/audits/$auditId'
    | '/_authenticated/agents/$id/containers/$containerId'
    | '/_authenticated/agents/$id/images/$imageId'
    | '/_authenticated/agents/$id/networks/$networkId'
    | '/_authenticated/agents/$id/volumes/$volumeName'
    | '/_authenticated/agents/$id/audit/'
    | '/_authenticated/agents/$id/audits/'
    | '/_authenticated/agents/$id/containers/'
    | '/_authenticated/agents/$id/images/'
    | '/_authenticated/agents/$id/networks/'
    | '/_authenticated/agents/$id/stacks/'
    | '/_authenticated/agents/$id/volumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyEmailChangeRoute: typeof VerifyEmailChangeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email-change': {
      id: '/verify-email-change'
      path: '/verify-email-change'
      fullPath: '/verify-email-change'
      preLoaderRoute: typeof VerifyEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/settings/sessions': {
      id: '/_authenticated/settings/sessions'
      path: '/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof AuthenticatedSettingsSessionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audits': {
      id: '/_authenticated/admin/audits'
      path: '/audits'
      fullPath: '/admin/audits'
      preLoaderRoute: typeof AuthenticatedAdminAuditsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/agents/$id/': {
      id: '/_authenticated/agents/$id/'
      path: '/'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AuthenticatedAgentsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/volumes': {
      id: '/_authenticated/agents/$id/volumes'
      path: '/volumes'
      fullPath: '/agents/$id/volumes'
      preLoaderRoute: typeof AuthenticatedAgentsIdVolumesRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/stacks': {
      id: '/_authenticated/agents/$id/stacks'
      path: '/stacks'
      fullPath: '/agents/$id/stacks'
      preLoaderRoute: typeof AuthenticatedAgentsIdStacksRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/networks': {
      id: '/_authenticated/agents/$id/networks'
      path: '/networks'
      fullPath: '/agents/$id/networks'
      preLoaderRoute: typeof AuthenticatedAgentsIdNetworksRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/images': {
      id: '/_authenticated/agents/$id/images'
      path: '/images'
      fullPath: '/agents/$id/images'
      preLoaderRoute: typeof AuthenticatedAgentsIdImagesRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/events': {
      id: '/_authenticated/agents/$id/events'
      path: '/events'
      fullPath: '/agents/$id/events'
      preLoaderRoute: typeof AuthenticatedAgentsIdEventsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/containers': {
      id: '/_authenticated/agents/$id/containers'
      path: '/containers'
      fullPath: '/agents/$id/containers'
      preLoaderRoute: typeof AuthenticatedAgentsIdContainersRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/audits': {
      id: '/_authenticated/agents/$id/audits'
      path: '/audits'
      fullPath: '/agents/$id/audits'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/audit': {
      id: '/_authenticated/agents/$id/audit'
      path: '/audit'
      fullPath: '/agents/$id/audit'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/volumes/': {
      id: '/_authenticated/agents/$id/volumes/'
      path: '/'
      fullPath: '/agents/$id/volumes/'
      preLoaderRoute: typeof AuthenticatedAgentsIdVolumesIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdVolumesRoute
    }
    '/_authenticated/agents/$id/stacks/': {
      id: '/_authenticated/agents/$id/stacks/'
      path: '/'
      fullPath: '/agents/$id/stacks/'
      preLoaderRoute: typeof AuthenticatedAgentsIdStacksIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdStacksRoute
    }
    '/_authenticated/agents/$id/networks/': {
      id: '/_authenticated/agents/$id/networks/'
      path: '/'
      fullPath: '/agents/$id/networks/'
      preLoaderRoute: typeof AuthenticatedAgentsIdNetworksIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdNetworksRoute
    }
    '/_authenticated/agents/$id/images/': {
      id: '/_authenticated/agents/$id/images/'
      path: '/'
      fullPath: '/agents/$id/images/'
      preLoaderRoute: typeof AuthenticatedAgentsIdImagesIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdImagesRoute
    }
    '/_authenticated/agents/$id/containers/': {
      id: '/_authenticated/agents/$id/containers/'
      path: '/'
      fullPath: '/agents/$id/containers/'
      preLoaderRoute: typeof AuthenticatedAgentsIdContainersIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdContainersRoute
    }
    '/_authenticated/agents/$id/audits/': {
      id: '/_authenticated/agents/$id/audits/'
      path: '/'
      fullPath: '/agents/$id/audits/'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditsIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdAuditsRoute
    }
    '/_authenticated/agents/$id/audit/': {
      id: '/_authenticated/agents/$id/audit/'
      path: '/'
      fullPath: '/agents/$id/audit/'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdAuditRoute
    }
    '/_authenticated/agents/$id/volumes/$volumeName': {
      id: '/_authenticated/agents/$id/volumes/$volumeName'
      path: '/$volumeName'
      fullPath: '/agents/$id/volumes/$volumeName'
      preLoaderRoute: typeof AuthenticatedAgentsIdVolumesVolumeNameRouteImport
      parentRoute: typeof AuthenticatedAgentsIdVolumesRoute
    }
    '/_authenticated/agents/$id/networks/$networkId': {
      id: '/_authenticated/agents/$id/networks/$networkId'
      path: '/$networkId'
      fullPath: '/agents/$id/networks/$networkId'
      preLoaderRoute: typeof AuthenticatedAgentsIdNetworksNetworkIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdNetworksRoute
    }
    '/_authenticated/agents/$id/images/$imageId': {
      id: '/_authenticated/agents/$id/images/$imageId'
      path: '/$imageId'
      fullPath: '/agents/$id/images/$imageId'
      preLoaderRoute: typeof AuthenticatedAgentsIdImagesImageIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdImagesRoute
    }
    '/_authenticated/agents/$id/containers/$containerId': {
      id: '/_authenticated/agents/$id/containers/$containerId'
      path: '/$containerId'
      fullPath: '/agents/$id/containers/$containerId'
      preLoaderRoute: typeof AuthenticatedAgentsIdContainersContainerIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdContainersRoute
    }
    '/_authenticated/agents/$id/audits/$auditId': {
      id: '/_authenticated/agents/$id/audits/$auditId'
      path: '/$auditId'
      fullPath: '/agents/$id/audits/$auditId'
      preLoaderRoute: typeof AuthenticatedAgentsIdAuditsAuditIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdAuditsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminAuditsRoute: typeof AuthenticatedAdminAuditsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminAuditsRoute: AuthenticatedAdminAuditsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsSessionsRoute: typeof AuthenticatedSettingsSessionsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsSessionsRoute: AuthenticatedSettingsSessionsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedAgentsIdAuditRouteChildren {
  AuthenticatedAgentsIdAuditIndexRoute: typeof AuthenticatedAgentsIdAuditIndexRoute
}

const AuthenticatedAgentsIdAuditRouteChildren: AuthenticatedAgentsIdAuditRouteChildren =
  {
    AuthenticatedAgentsIdAuditIndexRoute: AuthenticatedAgentsIdAuditIndexRoute,
  }

const AuthenticatedAgentsIdAuditRouteWithChildren =
  AuthenticatedAgentsIdAuditRoute._addFileChildren(
    AuthenticatedAgentsIdAuditRouteChildren,
  )

interface AuthenticatedAgentsIdAuditsRouteChildren {
  AuthenticatedAgentsIdAuditsAuditIdRoute: typeof AuthenticatedAgentsIdAuditsAuditIdRoute
  AuthenticatedAgentsIdAuditsIndexRoute: typeof AuthenticatedAgentsIdAuditsIndexRoute
}

const AuthenticatedAgentsIdAuditsRouteChildren: AuthenticatedAgentsIdAuditsRouteChildren =
  {
    AuthenticatedAgentsIdAuditsAuditIdRoute:
      AuthenticatedAgentsIdAuditsAuditIdRoute,
    AuthenticatedAgentsIdAuditsIndexRoute:
      AuthenticatedAgentsIdAuditsIndexRoute,
  }

const AuthenticatedAgentsIdAuditsRouteWithChildren =
  AuthenticatedAgentsIdAuditsRoute._addFileChildren(
    AuthenticatedAgentsIdAuditsRouteChildren,
  )

interface AuthenticatedAgentsIdContainersRouteChildren {
  AuthenticatedAgentsIdContainersContainerIdRoute: typeof AuthenticatedAgentsIdContainersContainerIdRoute
  AuthenticatedAgentsIdContainersIndexRoute: typeof AuthenticatedAgentsIdContainersIndexRoute
}

const AuthenticatedAgentsIdContainersRouteChildren: AuthenticatedAgentsIdContainersRouteChildren =
  {
    AuthenticatedAgentsIdContainersContainerIdRoute:
      AuthenticatedAgentsIdContainersContainerIdRoute,
    AuthenticatedAgentsIdContainersIndexRoute:
      AuthenticatedAgentsIdContainersIndexRoute,
  }

const AuthenticatedAgentsIdContainersRouteWithChildren =
  AuthenticatedAgentsIdContainersRoute._addFileChildren(
    AuthenticatedAgentsIdContainersRouteChildren,
  )

interface AuthenticatedAgentsIdImagesRouteChildren {
  AuthenticatedAgentsIdImagesImageIdRoute: typeof AuthenticatedAgentsIdImagesImageIdRoute
  AuthenticatedAgentsIdImagesIndexRoute: typeof AuthenticatedAgentsIdImagesIndexRoute
}

const AuthenticatedAgentsIdImagesRouteChildren: AuthenticatedAgentsIdImagesRouteChildren =
  {
    AuthenticatedAgentsIdImagesImageIdRoute:
      AuthenticatedAgentsIdImagesImageIdRoute,
    AuthenticatedAgentsIdImagesIndexRoute:
      AuthenticatedAgentsIdImagesIndexRoute,
  }

const AuthenticatedAgentsIdImagesRouteWithChildren =
  AuthenticatedAgentsIdImagesRoute._addFileChildren(
    AuthenticatedAgentsIdImagesRouteChildren,
  )

interface AuthenticatedAgentsIdNetworksRouteChildren {
  AuthenticatedAgentsIdNetworksNetworkIdRoute: typeof AuthenticatedAgentsIdNetworksNetworkIdRoute
  AuthenticatedAgentsIdNetworksIndexRoute: typeof AuthenticatedAgentsIdNetworksIndexRoute
}

const AuthenticatedAgentsIdNetworksRouteChildren: AuthenticatedAgentsIdNetworksRouteChildren =
  {
    AuthenticatedAgentsIdNetworksNetworkIdRoute:
      AuthenticatedAgentsIdNetworksNetworkIdRoute,
    AuthenticatedAgentsIdNetworksIndexRoute:
      AuthenticatedAgentsIdNetworksIndexRoute,
  }

const AuthenticatedAgentsIdNetworksRouteWithChildren =
  AuthenticatedAgentsIdNetworksRoute._addFileChildren(
    AuthenticatedAgentsIdNetworksRouteChildren,
  )

interface AuthenticatedAgentsIdStacksRouteChildren {
  AuthenticatedAgentsIdStacksIndexRoute: typeof AuthenticatedAgentsIdStacksIndexRoute
}

const AuthenticatedAgentsIdStacksRouteChildren: AuthenticatedAgentsIdStacksRouteChildren =
  {
    AuthenticatedAgentsIdStacksIndexRoute:
      AuthenticatedAgentsIdStacksIndexRoute,
  }

const AuthenticatedAgentsIdStacksRouteWithChildren =
  AuthenticatedAgentsIdStacksRoute._addFileChildren(
    AuthenticatedAgentsIdStacksRouteChildren,
  )

interface AuthenticatedAgentsIdVolumesRouteChildren {
  AuthenticatedAgentsIdVolumesVolumeNameRoute: typeof AuthenticatedAgentsIdVolumesVolumeNameRoute
  AuthenticatedAgentsIdVolumesIndexRoute: typeof AuthenticatedAgentsIdVolumesIndexRoute
}

const AuthenticatedAgentsIdVolumesRouteChildren: AuthenticatedAgentsIdVolumesRouteChildren =
  {
    AuthenticatedAgentsIdVolumesVolumeNameRoute:
      AuthenticatedAgentsIdVolumesVolumeNameRoute,
    AuthenticatedAgentsIdVolumesIndexRoute:
      AuthenticatedAgentsIdVolumesIndexRoute,
  }

const AuthenticatedAgentsIdVolumesRouteWithChildren =
  AuthenticatedAgentsIdVolumesRoute._addFileChildren(
    AuthenticatedAgentsIdVolumesRouteChildren,
  )

interface AuthenticatedAgentsIdRouteChildren {
  AuthenticatedAgentsIdAuditRoute: typeof AuthenticatedAgentsIdAuditRouteWithChildren
  AuthenticatedAgentsIdAuditsRoute: typeof AuthenticatedAgentsIdAuditsRouteWithChildren
  AuthenticatedAgentsIdContainersRoute: typeof AuthenticatedAgentsIdContainersRouteWithChildren
  AuthenticatedAgentsIdEventsRoute: typeof AuthenticatedAgentsIdEventsRoute
  AuthenticatedAgentsIdImagesRoute: typeof AuthenticatedAgentsIdImagesRouteWithChildren
  AuthenticatedAgentsIdNetworksRoute: typeof AuthenticatedAgentsIdNetworksRouteWithChildren
  AuthenticatedAgentsIdStacksRoute: typeof AuthenticatedAgentsIdStacksRouteWithChildren
  AuthenticatedAgentsIdVolumesRoute: typeof AuthenticatedAgentsIdVolumesRouteWithChildren
  AuthenticatedAgentsIdIndexRoute: typeof AuthenticatedAgentsIdIndexRoute
}

const AuthenticatedAgentsIdRouteChildren: AuthenticatedAgentsIdRouteChildren = {
  AuthenticatedAgentsIdAuditRoute: AuthenticatedAgentsIdAuditRouteWithChildren,
  AuthenticatedAgentsIdAuditsRoute:
    AuthenticatedAgentsIdAuditsRouteWithChildren,
  AuthenticatedAgentsIdContainersRoute:
    AuthenticatedAgentsIdContainersRouteWithChildren,
  AuthenticatedAgentsIdEventsRoute: AuthenticatedAgentsIdEventsRoute,
  AuthenticatedAgentsIdImagesRoute:
    AuthenticatedAgentsIdImagesRouteWithChildren,
  AuthenticatedAgentsIdNetworksRoute:
    AuthenticatedAgentsIdNetworksRouteWithChildren,
  AuthenticatedAgentsIdStacksRoute:
    AuthenticatedAgentsIdStacksRouteWithChildren,
  AuthenticatedAgentsIdVolumesRoute:
    AuthenticatedAgentsIdVolumesRouteWithChildren,
  AuthenticatedAgentsIdIndexRoute: AuthenticatedAgentsIdIndexRoute,
}

const AuthenticatedAgentsIdRouteWithChildren =
  AuthenticatedAgentsIdRoute._addFileChildren(
    AuthenticatedAgentsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRouteWithChildren
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRouteWithChildren,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyEmailChangeRoute: VerifyEmailChangeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
